/**
 * Generates `src/abi.ts` from the Foundry build artifact of PaymentRouter.sol.
 *
 * Reads `../payment-router/out/PaymentRouter.sol/PaymentRouter.json`, extracts
 * its `abi` array, validates the public surface downstream RFCs depend on
 * (`payEth`, `payERC20`, `PaymentCompleted`), and writes a `const`-asserted TS
 * module so viem can narrow function signatures and event topics at compile
 * time. Run via `bun run build:abi` (root: `bun run build:contracts-abi`).
 *
 * Re-run after any change to `src/PaymentRouter.sol` and commit the result — the
 * package typechecks against the committed ABI, so a fresh clone needs no build
 * step before `turbo typecheck`.
 */

const ARTIFACT_REL = "../../payment-router/out/PaymentRouter.sol/PaymentRouter.json";
const OUT_REL = "../src/abi.ts";

const here = import.meta.dir;
const artifactPath = `${here}/${ARTIFACT_REL}`;
const outPath = `${here}/${OUT_REL}`;

interface AbiEntry {
  readonly type: string;
  readonly name?: string;
}

const artifact = (await Bun.file(artifactPath).json()) as { abi: readonly AbiEntry[] };
const abi = artifact.abi;

const names = new Set(abi.map((entry) => `${entry.type}:${entry.name ?? ""}`));
const required = ["function:payEth", "function:payERC20", "event:PaymentCompleted"] as const;
const missing = required.filter((signature) => !names.has(signature));
if (missing.length > 0) {
  throw new Error(
    `PaymentRouter ABI is missing required entries: ${missing.join(", ")}. ` +
      `Rebuild the contract (forge build) before regenerating the ABI.`,
  );
}

const body = JSON.stringify(abi, null, 2);
const header = [
  "// GENERATED by scripts/generate-abi.ts — do not edit by hand.",
  "// Source: packages/contracts/payment-router/out/PaymentRouter.sol/PaymentRouter.json",
  "// Regenerate: `bun run build:contracts-abi` from the repo root.",
  "",
  `export const paymentRouterAbi = ${body} as const;`,
  "",
].join("\n");

await Bun.write(outPath, header);
console.log(`wrote ${outPath} (${abi.length} entries)`);
