/**
 * Generates `vectors/order-hash.json` — the EIP-712 order-hash test vectors
 * (#24 acceptance: "order-hash test vectors exported for the TS side").
 *
 * The vectors are hashed here with viem, from the `ORDER_TYPES` that
 * `@mayarin/quote` (#40) declares. `test/order-vectors.test.ts` re-derives them
 * on the TS side and `PaymentRouter.t.sol` re-derives them on the contract side,
 * both against this one committed file. That closes the loop #40 asked for: if
 * the quote engine's field list, the contract's typehash, or either domain ever
 * drift apart, one of the two suites fails instead of signatures silently
 * failing verification in production.
 *
 * The domain is fixed here (a placeholder chain id and verifying contract)
 * because the vector must be reproducible; a live deployment substitutes its own
 * chain id and address into the same formula.
 *
 * Run via `bun run build:order-vectors`.
 */

import { ORDER_DOMAIN_NAME, ORDER_DOMAIN_VERSION, ORDER_TYPES } from "@mayarin/quote";
import { hashDomain, hashStruct, hashTypedData, keccak256, toHex } from "viem";

const OUT_REL = "../vectors/order-hash.json";

const domain = {
  name: ORDER_DOMAIN_NAME,
  version: ORDER_DOMAIN_VERSION,
  chainId: 84532n, // Base Sepolia — the first deploy target (#29)
  verifyingContract: "0x00000000000000000000000000000000000c0de5" as const,
} as const;

const order = {
  intentId: "0x0000000000000000000000000000000000000000000000000000000000000001",
  minOut: 100_000_000n, // 100 USDC, 6 decimals
  fee: 1_000_000n, // 1 USDC
  merchantSafe: "0x000000000000000000000000000000000000bEEF",
  refundTo: "0x000000000000000000000000000000000000cafE",
  deadline: 57005n, // 0xDEAD — a literal, so the vector never depends on a clock
} as const;

const typeString =
  "Order(bytes32 intentId,uint256 minOut,uint256 fee,address merchantSafe,address refundTo,uint256 deadline)";

const vectors = {
  _comment:
    "GENERATED by scripts/generate-order-vectors.ts — do not edit by hand. " +
    "Asserted from TypeScript in test/order-vectors.test.ts and from Solidity in " +
    "packages/contracts/payment-router/test/PaymentRouter.t.sol.",
  typeString,
  typeHash: keccak256(toHex(typeString)),
  domain: {
    name: domain.name,
    version: domain.version,
    chainId: Number(domain.chainId),
    verifyingContract: domain.verifyingContract,
  },
  domainSeparator: hashDomain({
    domain,
    types: {
      EIP712Domain: [
        { name: "name", type: "string" },
        { name: "version", type: "string" },
        { name: "chainId", type: "uint256" },
        { name: "verifyingContract", type: "address" },
      ],
    },
  }),
  order: {
    intentId: order.intentId,
    minOut: order.minOut.toString(),
    fee: order.fee.toString(),
    merchantSafe: order.merchantSafe,
    refundTo: order.refundTo,
    deadline: order.deadline.toString(),
  },
  structHash: hashStruct({ data: order, primaryType: "Order", types: ORDER_TYPES }),
  digest: hashTypedData({ domain, types: ORDER_TYPES, primaryType: "Order", message: order }),
};

const outPath = `${import.meta.dir}/${OUT_REL}`;
await Bun.write(outPath, `${JSON.stringify(vectors, null, 2)}\n`);
console.log(`wrote ${outPath}`);
