import type { OpenAPIV3_1 } from "fumadocs-openapi";
import { createOpenAPI, type OpenAPIOptions } from "fumadocs-openapi/server";
// Generated by `bun run --cwd apps/docs generate` from scripts/generate-openapi.ts.
// Do not edit by hand; regenerate and commit the result.
import mayarinOpenAPI from "./openapi.json" with { type: "json" };

const openapiInput = {
  mayarin: mayarinOpenAPI as unknown as OpenAPIV3_1.Document,
} as unknown as Exclude<NonNullable<OpenAPIOptions["input"]>, string[]>;

export const openapi = createOpenAPI({ input: openapiInput });
