/**
 * Generates `packages/contracts/payment-router/test/fixtures/router-calldata.json`
 * — the cross-language check for the #49 call builder.
 *
 * The TS builder encodes; `test/RouterCalldata.t.sol` verifies from the contract
 * side, two ways. It re-encodes the same inputs with `abi.encodeWithSelector` and
 * asserts the bytes are identical, and it calls the deployed router with the
 * fixture bytes verbatim and asserts the revert is `InvalidSigner` — which only
 * happens if the selector matched a real function, the ABI decode succeeded, and
 * every field landed where the contract reads it. A malformed encoding fails
 * earlier and differently.
 *
 * The signature is a dummy: it cannot be valid, because the EIP-712 domain binds
 * to the router's deployed address and this fixture is address-agnostic. That the
 * call reaches signature verification at all is the point.
 *
 * Run via `bun run build:router-calldata`.
 */

import type { Order } from "@mayarin/contracts";
import { privateKeyToAccount } from "viem/accounts";
import { buildPayERC20Call, buildPayEthCall, type Permit2Single } from "../src/payment-router.ts";

const OUT_REL = "../../../contracts/payment-router/test/fixtures/router-calldata.json";

const paymentRouter = "0x00000000000000000000000000000000000c0de5" as const;
const dex = "0x00000000000000000000000000000000000000d3" as const;
const weth = "0x000000000000000000000000000000000000e701" as const;
const usdc = "0x000000000000000000000000000000000000c0de" as const;

/** Far-future deadline, so the contract gets past the expiry check to the signature. */
const order: Order = {
  intentId: "0x0000000000000000000000000000000000000000000000000000000000000001",
  minOut: 100_000_000n,
  fee: 1_000_000n,
  merchantSafe: "0x000000000000000000000000000000000000bEEF",
  refundTo: "0x000000000000000000000000000000000000cafE",
  deadline: 281_474_976_710_655n, // type(uint48).max
};

/**
 * A well-formed signature from a throwaway key over an unrelated message. It is
 * structurally valid — `ECDSA.recover` returns an address rather than reverting —
 * but recovers to nobody the router trusts, so the contract-side check lands on
 * `InvalidSigner`. A malformed 65 bytes would revert inside OpenZeppelin's ECDSA
 * instead, which proves less: it would not show the order struct was read.
 */
const signature = await privateKeyToAccount(`0x${"11".repeat(32)}`).signMessage({
  message: "mayarin router calldata fixture",
});
const permitSignature = `0x${"cd".repeat(65)}` as const;
const swapCallData = "0xdeadbeefcafe" as const;
const value = 1_000_000_000_000_000_000n;

const crossAssetPermit: Permit2Single = {
  token: weth,
  amount: 1_000_000_000_000_000_000n,
  expiration: 2_000_000_000,
  nonce: 7,
  spender: paymentRouter,
  sigDeadline: 2_000_000_000n,
};

const payEth = buildPayEthCall({
  paymentRouter,
  order,
  signature,
  route: { router: dex, callData: swapCallData },
  value,
});

const payErc20Cross = buildPayERC20Call({
  paymentRouter,
  order,
  signature,
  permit: crossAssetPermit,
  permitSignature,
  route: { router: dex, callData: swapCallData },
});

const payErc20Same = buildPayERC20Call({
  paymentRouter,
  order,
  signature,
  permit: { ...crossAssetPermit, token: usdc },
  permitSignature,
});

const fixture = {
  _comment:
    "GENERATED by packages/providers/evm/scripts/generate-router-calldata.ts — do not edit by hand. " +
    "Verified from Solidity in packages/contracts/payment-router/test/RouterCalldata.t.sol.",
  order: {
    intentId: order.intentId,
    minOut: order.minOut.toString(),
    fee: order.fee.toString(),
    merchantSafe: order.merchantSafe,
    refundTo: order.refundTo,
    deadline: order.deadline.toString(),
  },
  signature,
  permitSignature,
  dex,
  weth,
  usdc,
  swapCallData,
  value: value.toString(),
  permit: {
    token: crossAssetPermit.token,
    amount: crossAssetPermit.amount.toString(),
    expiration: crossAssetPermit.expiration,
    nonce: crossAssetPermit.nonce,
    spender: crossAssetPermit.spender,
    sigDeadline: crossAssetPermit.sigDeadline.toString(),
  },
  payEthCalldata: payEth.data,
  payErc20CrossCalldata: payErc20Cross.data,
  payErc20SameCalldata: payErc20Same.data,
};

const outPath = `${import.meta.dir}/${OUT_REL}`;
await Bun.write(outPath, `${JSON.stringify(fixture, null, 2)}\n`);
console.log(`wrote ${outPath}`);
